CREATE TABLE BankAccount (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  accountNumber VARCHAR(100),
  bankName VARCHAR(100),
  bankCode VARCHAR(100),
  iban VARCHAR(100),
  bic VARCHAR(100),
  PRIMARY KEY(id)
);

CREATE TABLE TaxRate (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  shortName VARCHAR(50) NOT NULL,
  longName VARCHAR(100) NOT NULL,
  rate DECIMAL(6,3) NOT NULL,
  isVAT BOOLEAN NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE UserProfile (
  name VARCHAR(50) NOT NULL,
  description VARCHAR(1000),
  primaryAddress INTEGER REFERENCES Address(id),
  taxId VARCHAR(100),
  bankAccount INTEGER REFERENCES BankAccount(id),
  PRIMARY KEY(name)
);